# Generated by Django 6.0 on 2026-02-15 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('productivity', 'Productivity'), ('expense', 'Expense'), ('fitness', 'Fitness'), ('mental', 'Mental Wellness'), ('general', 'General')], default='general', max_length=20)),
                ('severity', models.CharField(choices=[('good', 'Good'), ('warning', 'Warning'), ('critical', 'Critical')], default='good', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('work_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😔 Sad'), ('stressed', '😫 Stressed'), ('energetic', '😎 Energetic')], default='neutral', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Entries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
