# Generated by Django 6.0 on 2026-02-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default Blue'), ('dark', 'Dark Mode'), ('ocean', 'Ocean Breeze'), ('sunset', 'Sunset Glow'), ('forest', 'Forest Green'), ('lavender', 'Lavender Dream')], default='default', max_length=20),
        ),
    ]
