# Generated by Django 4.2.10 on 2026-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analytics_mood_data_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['user', 'date'], name='analyzer_da_user_id_94e429_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyentry',
            index=models.Index(fields=['date'], name='analyzer_da_date_eb2d07_idx'),
        ),
    ]
